# Override for development
services:

  backend:
    environment:
      - PUBLIC_URL=http://localhost:8055

      - AUTH_MICROSOFT_REDIRECT_ALLOW_LIST=http://localhost:3000/login

      - SESSION_COOKIE_DOMAIN=localhost
      - SESSION_COOKIE_SECURE=false
      - SESSION_COOKIE_SAME_SITE=lax

      - EXTENSIONS_AUTO_RELOAD=true

  frontend:
    build: 
      target: development
    volumes:
      - ./frontend:/app

  oidc_proxy:
    ports:
      - "8060:8060"
    build:
      target: development
    volumes:
      - ./oidc_proxy:/app