# Override for development
services:

  oidc_proxy:
    build:
      target: development
    stop_grace_period: 500ms
    ports:
      - "8060:8060"
    volumes:
      - ./oidc_proxy:/app
    user: ${UID:-1000}:${GID:-1000}


  storage:
    stop_grace_period: 500ms
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console
    environment:
      - MINIO_DEBUG=true

  backend:
    stop_grace_period: 500ms
    build:
      target: development
    ports:
      - "8055:8055"
    volumes:
      - ./backend/schema-sync:/directus/schema-sync
      - ./backend/extensions/hooks:/directus/extensions
    environment:
      - SESSION_COOKIE_DOMAIN=localhost
      - SESSION_COOKIE_SECURE=false
      - SESSION_COOKIE_SAME_SITE=lax

      - AUTH_DISABLE_DEFAULT=false
      # uncomment to make new microsoft accounts an admin by default
      # helps to develop without having to care about permissions
      # - AUTH_MICROSOFT_DEFAULT_ROLE_ID=96fe793c-a8e4-4ec4-84c1-a7f139762227

      - EXTENSIONS_MUST_LOAD=false
      - EXTENSIONS_AUTO_RELOAD=true
      - SCHEMA_SYNC=BOTH
    user: ${UID:-1000}:${GID:-1000}

  frontend:
    stop_grace_period: 500ms
    build: 
      target: development
    volumes:
      - ./frontend:/app
      - ./backend/schema-sync/data:/backend/schema-sync/data
    user: ${UID:-1000}:${GID:-1000}

  database-explorer:
    stop_grace_period: 500ms
    image: sosedoff/pgweb:latest
    restart: unless-stopped
    ports:
      - "9003:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - app_network
    env_file:
      - .env
